// Generated by framecc; DO NOT EDIT
package protocol

import (
	"github.com/sinusoids/gem/gem/encoding"
)

type TestFrame AnonStruct_45

type EmbeddedStruct struct {
	A encoding.Int32
	B encoding.Int32
	C encoding.Int32
}

func (struc *EmbeddedStruct) Encode(buf *bytes.Buffer, flags interface{}) (err error) {
	err = struc.A.Encode(buf, encoding.IntegerFlag(encode.IntLittleEndian))
	if err != nil {
		return err
	}

	err = struc.B.Encode(buf, encoding.IntegerFlag(encode.IntOffset128|encode.IntPDPEndian))
	if err != nil {
		return err
	}

	err = struc.C.Encode(buf, encoding.IntegerFlag())
	if err != nil {
		return err
	}

}

func (struc *EmbeddedStruct) Decode(buf *bytes.Buffer, flags interface{}) (err error) {
	err = struc.A.Decode(buf, encoding.IntegerFlag(encode.IntLittleEndian))
	if err != nil {
		return err
	}

	err = struc.B.Decode(buf, encoding.IntegerFlag(encode.IntOffset128|encode.IntPDPEndian))
	if err != nil {
		return err
	}

	err = struc.C.Decode(buf, encoding.IntegerFlag())
	if err != nil {
		return err
	}

}

type AnonStruct_45 struct {
	Message  encoding.JString
	Values8  [4]encoding.Int16
	Values16 [2]encoding.Int16
	Struc    EmbeddedStruct
}

func (struc *AnonStruct_45) Encode(buf *bytes.Buffer, flags interface{}) (err error) {
	err = struc.Message.Encode(buf, 256)
	if err != nil {
		return err
	}

	for i := 0; i < 4; i++ {
		err = struc.Values8[i].Encode(buf, encoding.IntegerFlag())
		if err != nil {
			return err
		}
	}

	for i := 0; i < 2; i++ {
		err = struc.Values16[i].Encode(buf, encoding.IntegerFlag())
		if err != nil {
			return err
		}
	}

	err = struc.Struc.Encode(buf, encoding.NilFlags)
	if err != nil {
		return err
	}

}

func (struc *AnonStruct_45) Decode(buf *bytes.Buffer, flags interface{}) (err error) {
	err = struc.Message.Decode(buf, 256)
	if err != nil {
		return err
	}

	for i := 0; i < 4; i++ {
		err = struc.Values8[i].Decode(buf, encoding.IntegerFlag())
		if err != nil {
			return err
		}
	}

	for i := 0; i < 2; i++ {
		err = struc.Values16[i].Decode(buf, encoding.IntegerFlag())
		if err != nil {
			return err
		}
	}

	err = struc.Struc.Decode(buf, encoding.NilFlags)
	if err != nil {
		return err
	}

}
