// Generated by gopygen; DO NOT EDIT
package archive

import (
	"fmt"
	"github.com/sinusoids/gem/gem/runite"
	"github.com/sinusoids/gem/gem/runite/format/rt3"
	"net"

	"gopkg.in/tomb.v2"

	"github.com/qur/gopy/lib"
	"github.com/tgascoigne/gopygen/gopygen"
)

// Sometimes we might generate code which doesn't use some of the above imports
// Use them here just in case
var _ = fmt.Sprintf("")
var _ = gopygen.Dummy

var ServerDef = py.Class{
	Name:    "Server",
	Flags:   py.TPFLAGS_BASETYPE,
	Pointer: (*Server)(nil),
}

// Registers this type with a python module
func RegisterServer(module *py.Module) error {
	var err error
	var class *py.Type
	if class, err = ServerDef.Create(); err != nil {
		return err
	}

	if err = module.AddObject("Server", class); err != nil {
		return err
	}

	return nil
}

func (obj *Server) PyGet_laddr() (py.Object, error) {
	return gopygen.TypeConvOut(obj.laddr, "string")
}

func (obj *Server) PySet_laddr(arg py.Object) error {
	arg.Incref()
	val, err := gopygen.TypeConvIn(arg, "string")
	if err != nil {
		return err
	}

	if _, ok := val.(py.Object); ok {
		// If we're not converting it from a python object, we should refcount it properly
		val.(py.Object).Incref()
	}
	arg.Decref()

	var tmp interface{}
	tmp = &obj.laddr
	obj.laddr = val.(string)

	if oldObj, ok := tmp.(py.Object); ok {
		// If we're not converting it from a python object, we should refcount it properly
		oldObj.Decref()
	}
	return nil
}

func (obj *Server) PyGet_ln() (py.Object, error) {
	return gopygen.TypeConvOut(obj.ln, "net.Listener")
}

func (obj *Server) PySet_ln(arg py.Object) error {
	arg.Incref()
	val, err := gopygen.TypeConvIn(arg, "net.Listener")
	if err != nil {
		return err
	}

	if _, ok := val.(py.Object); ok {
		// If we're not converting it from a python object, we should refcount it properly
		val.(py.Object).Incref()
	}
	arg.Decref()

	var tmp interface{}
	tmp = &obj.ln
	obj.ln = val.(net.Listener)

	if oldObj, ok := tmp.(py.Object); ok {
		// If we're not converting it from a python object, we should refcount it properly
		oldObj.Decref()
	}
	return nil
}

func (obj *Server) PyGet_archives() (py.Object, error) {
	return gopygen.TypeConvOut(obj.archives, "*rt3.ArchiveFS")
}

func (obj *Server) PySet_archives(arg py.Object) error {
	arg.Incref()
	val, err := gopygen.TypeConvIn(arg, "*rt3.ArchiveFS")
	if err != nil {
		return err
	}

	if _, ok := val.(py.Object); ok {
		// If we're not converting it from a python object, we should refcount it properly
		val.(py.Object).Incref()
	}
	arg.Decref()

	var tmp interface{}
	tmp = &obj.archives
	obj.archives = val.(*rt3.ArchiveFS)

	if oldObj, ok := tmp.(py.Object); ok {
		// If we're not converting it from a python object, we should refcount it properly
		oldObj.Decref()
	}
	return nil
}

func (obj *Server) PyGet_t() (py.Object, error) {
	return gopygen.TypeConvOut(obj.t, "tomb.Tomb")
}

func (obj *Server) PySet_t(arg py.Object) error {
	arg.Incref()
	val, err := gopygen.TypeConvIn(arg, "tomb.Tomb")
	if err != nil {
		return err
	}

	if _, ok := val.(py.Object); ok {
		// If we're not converting it from a python object, we should refcount it properly
		val.(py.Object).Incref()
	}
	arg.Decref()

	var tmp interface{}
	tmp = &obj.t
	obj.t = val.(tomb.Tomb)

	if oldObj, ok := tmp.(py.Object); ok {
		// If we're not converting it from a python object, we should refcount it properly
		oldObj.Decref()
	}
	return nil
}

func (s *Server) Py_Start(_args *py.Tuple, kwds *py.Dict) (py.Object, error) {
	lock := py.NewLock()
	defer lock.Unlock()

	var err error
	_ = err
	args := _args.Slice()
	if len(args) != 2 {
		return nil, fmt.Errorf("Py_Start: parameter length mismatch")
	}
	// Convert parameters

	args[0].Incref()
	in_0, err := gopygen.TypeConvIn(args[0], "string")
	if err != nil {
		return nil, err
	}

	args[1].Incref()
	in_1, err := gopygen.TypeConvIn(args[1], "*runite.Context")
	if err != nil {
		return nil, err
	}

	// Make the function call

	res0 := s.Start(in_0.(string), in_1.(*runite.Context))

	// Remove local references

	args[0].Decref()

	args[1].Decref()

	out_0, err := gopygen.TypeConvOut(res0, "error")
	if err != nil {
		return nil, err
	}
	out_0.Incref()

	return out_0, nil

}

func (s *Server) Py_Stop(_args *py.Tuple, kwds *py.Dict) (py.Object, error) {
	lock := py.NewLock()
	defer lock.Unlock()

	var err error
	_ = err
	args := _args.Slice()
	if len(args) != 0 {
		return nil, fmt.Errorf("Py_Stop: parameter length mismatch")
	}
	// Convert parameters

	// Make the function call

	res0 := s.Stop()

	// Remove local references

	out_0, err := gopygen.TypeConvOut(res0, "error")
	if err != nil {
		return nil, err
	}
	out_0.Incref()

	return out_0, nil

}
