// Code generated by gem_gen; DO NOT EDIT.
package protocol_os_163

import (
	"fmt"

	"github.com/gemrs/gem/gem/core/encoding"
	"github.com/gemrs/gem/gem/game/server"
	"github.com/gemrs/gem/gem/protocol"
)

var InboundTakeGroundItemDefinition = InboundPacketDefinition{
	Number: 33,
	Size:   SzFixed,
}

var InboundPlayerWalkDefinition = InboundPacketDefinition{
	Number: 94,
	Size:   SzVar8,
}

var InboundInventoryAction2Definition = InboundPacketDefinition{
	Number: 91,
	Size:   SzFixed,
}

var InboundInventoryAction4Definition = InboundPacketDefinition{
	Number: 58,
	Size:   SzFixed,
}

var OutboundSkillDefinition = OutboundPacketDefinition{
	Number: 57,
	Size:   SzFixed,
}

var OutboundChatMessageDefinition = OutboundPacketDefinition{
	Number: 39,
	Size:   SzVar8,
}

var OutboundSetRootInterfaceDefinition = OutboundPacketDefinition{
	Number: 47,
	Size:   SzFixed,
}

var InboundInventoryAction3Definition = InboundPacketDefinition{
	Number: 42,
	Size:   SzFixed,
}

var InboundKeyPressDefinition = InboundPacketDefinition{
	Number: 1,
	Size:   SzVar16,
}

var OutboundSetUpdatingTileDefinition = OutboundPacketDefinition{
	Number: 30,
	Size:   SzFixed,
}

var InboundChatMessageDefinition = InboundPacketDefinition{
	Number: 14,
	Size:   SzVar8,
}

var InboundPingDefinition = InboundPacketDefinition{
	Number: 89,
	Size:   SzFixed,
}

var OutboundRemoveGroundItemDefinition = OutboundPacketDefinition{
	Number: 22,
	Size:   SzFixed,
}

var OutboundSetInterfaceDefinition = OutboundPacketDefinition{
	Number: 67,
	Size:   SzFixed,
}

var OutboundScriptEventDefinition = OutboundPacketDefinition{
	Number: 54,
	Size:   SzVar16,
}

var InboundInventoryAction5Definition = InboundPacketDefinition{
	Number: 59,
	Size:   SzFixed,
}

var OutboundUpdateInventoryItemDefinition = OutboundPacketDefinition{
	Number: 56,
	Size:   SzVar16,
}

var InboundInventoryAction1Definition = InboundPacketDefinition{
	Number: 48,
	Size:   SzFixed,
}

var InboundInventorySwapItemDefinition = InboundPacketDefinition{
	Number: 38,
	Size:   SzFixed,
}

var PlayerUpdateDefinition = OutboundPacketDefinition{
	Number: 3,
	Size:   SzVar16,
}

var OutboundRegionUpdateDefinition = OutboundPacketDefinition{
	Number: 79,
	Size:   SzVar16,
}

var InboundMouseClickDefinition = InboundPacketDefinition{
	Number: 3,
	Size:   SzFixed,
}

var OutboundCreateGroundItemDefinition = OutboundPacketDefinition{
	Number: 10,
	Size:   SzFixed,
}

var InboundCommandDefinition = InboundPacketDefinition{
	Number: 13,
	Size:   SzVar8,
}

var InboundPlayerWalkMapDefinition = InboundPacketDefinition{
	Number: 4,
	Size:   SzVar8,
}

var InboundMouseMovementDefinition = InboundPacketDefinition{
	Number: 63,
	Size:   SzVar8,
}

var InboundWindowFocusDefinition = InboundPacketDefinition{
	Number: 5,
	Size:   SzFixed,
}

var InboundCameraMovementDefinition = InboundPacketDefinition{
	Number: 82,
	Size:   SzFixed,
}

var OutboundUpdateAllInventoryItemsDefinition = OutboundPacketDefinition{
	Number: 27,
	Size:   SzVar16,
}

var inboundPacketBuilders = map[int]func() encoding.Decodable{

	33: func() encoding.Decodable {
		return &PacketHeader{
			Number: InboundTakeGroundItemDefinition.Number,
			Size:   InboundTakeGroundItemDefinition.Size,
			Object: new(InboundTakeGroundItem),
		}
	},

	94: func() encoding.Decodable {
		return &PacketHeader{
			Number: InboundPlayerWalkDefinition.Number,
			Size:   InboundPlayerWalkDefinition.Size,
			Object: new(InboundPlayerWalk),
		}
	},

	91: func() encoding.Decodable {
		return &PacketHeader{
			Number: InboundInventoryAction2Definition.Number,
			Size:   InboundInventoryAction2Definition.Size,
			Object: new(InboundInventoryAction2),
		}
	},

	58: func() encoding.Decodable {
		return &PacketHeader{
			Number: InboundInventoryAction4Definition.Number,
			Size:   InboundInventoryAction4Definition.Size,
			Object: new(InboundInventoryAction4),
		}
	},

	42: func() encoding.Decodable {
		return &PacketHeader{
			Number: InboundInventoryAction3Definition.Number,
			Size:   InboundInventoryAction3Definition.Size,
			Object: new(InboundInventoryAction3),
		}
	},

	1: func() encoding.Decodable {
		return &PacketHeader{
			Number: InboundKeyPressDefinition.Number,
			Size:   InboundKeyPressDefinition.Size,
			Object: new(InboundKeyPress),
		}
	},

	14: func() encoding.Decodable {
		return &PacketHeader{
			Number: InboundChatMessageDefinition.Number,
			Size:   InboundChatMessageDefinition.Size,
			Object: new(InboundChatMessage),
		}
	},

	89: func() encoding.Decodable {
		return &PacketHeader{
			Number: InboundPingDefinition.Number,
			Size:   InboundPingDefinition.Size,
			Object: new(InboundPing),
		}
	},

	59: func() encoding.Decodable {
		return &PacketHeader{
			Number: InboundInventoryAction5Definition.Number,
			Size:   InboundInventoryAction5Definition.Size,
			Object: new(InboundInventoryAction5),
		}
	},

	48: func() encoding.Decodable {
		return &PacketHeader{
			Number: InboundInventoryAction1Definition.Number,
			Size:   InboundInventoryAction1Definition.Size,
			Object: new(InboundInventoryAction1),
		}
	},

	38: func() encoding.Decodable {
		return &PacketHeader{
			Number: InboundInventorySwapItemDefinition.Number,
			Size:   InboundInventorySwapItemDefinition.Size,
			Object: new(InboundInventorySwapItem),
		}
	},

	3: func() encoding.Decodable {
		return &PacketHeader{
			Number: InboundMouseClickDefinition.Number,
			Size:   InboundMouseClickDefinition.Size,
			Object: new(InboundMouseClick),
		}
	},

	13: func() encoding.Decodable {
		return &PacketHeader{
			Number: InboundCommandDefinition.Number,
			Size:   InboundCommandDefinition.Size,
			Object: new(InboundCommand),
		}
	},

	4: func() encoding.Decodable {
		return &PacketHeader{
			Number: InboundPlayerWalkMapDefinition.Number,
			Size:   InboundPlayerWalkMapDefinition.Size,
			Object: new(InboundPlayerWalkMap),
		}
	},

	63: func() encoding.Decodable {
		return &PacketHeader{
			Number: InboundMouseMovementDefinition.Number,
			Size:   InboundMouseMovementDefinition.Size,
			Object: new(InboundMouseMovement),
		}
	},

	5: func() encoding.Decodable {
		return &PacketHeader{
			Number: InboundWindowFocusDefinition.Number,
			Size:   InboundWindowFocusDefinition.Size,
			Object: new(InboundWindowFocus),
		}
	},

	82: func() encoding.Decodable {
		return &PacketHeader{
			Number: InboundCameraMovementDefinition.Number,
			Size:   InboundCameraMovementDefinition.Size,
			Object: new(InboundCameraMovement),
		}
	},
}

func (p protocolImpl) Decode(message encoding.Decodable) server.Message {
	switch message := message.(type) {

	case *InboundTakeGroundItem:
		return (*protocol.InboundTakeGroundItem)(message)

	case *InboundPlayerWalk:
		return (*protocol.InboundPlayerWalk)(message)

	case *InboundInventoryAction2:
		return (*protocol.InboundInventoryAction)(message)

	case *InboundInventoryAction4:
		return (*protocol.InboundInventoryAction)(message)

	case *InboundInventoryAction3:
		return (*protocol.InboundInventoryAction)(message)

	case *InboundKeyPress:
		return (*protocol.InboundKeyPress)(message)

	case *InboundChatMessage:
		return (*protocol.InboundChatMessage)(message)

	case *InboundPing:
		return (*protocol.InboundPing)(message)

	case *InboundInventoryAction5:
		return (*protocol.InboundInventoryAction)(message)

	case *InboundInventoryAction1:
		return (*protocol.InboundInventoryAction)(message)

	case *InboundInventorySwapItem:
		return (*protocol.InboundInventorySwapItem)(message)

	case *InboundMouseClick:
		return (*protocol.InboundMouseClick)(message)

	case *InboundCommand:
		return (*protocol.InboundCommand)(message)

	case *InboundPlayerWalkMap:
		return (*protocol.InboundPlayerWalk)(message)

	case *InboundMouseMovement:
		return (*protocol.InboundMouseMovement)(message)

	case *InboundWindowFocus:
		return (*protocol.InboundWindowFocus)(message)

	case *InboundCameraMovement:
		return (*protocol.InboundCameraMovement)(message)

	case *UnknownPacket:
		return (*protocol.UnknownPacket)(message)

	case *PacketHeader:
		return p.Decode(message.Object.(encoding.Decodable))
	}
	panic(fmt.Sprintf("cannot decode %T", message))
}

func (protocolImpl) Encode(message server.Message) encoding.Encodable {
	switch message := message.(type) {

	case protocol.OutboundSkill:
		return OutboundSkillDefinition.Pack(OutboundSkill(message))

	case protocol.OutboundChatMessage:
		return OutboundChatMessageDefinition.Pack(OutboundChatMessage(message))

	case protocol.OutboundSetRootInterface:
		return OutboundSetRootInterfaceDefinition.Pack(OutboundSetRootInterface(message))

	case protocol.OutboundSetUpdatingTile:
		return OutboundSetUpdatingTileDefinition.Pack(OutboundSetUpdatingTile(message))

	case protocol.OutboundRemoveGroundItem:
		return OutboundRemoveGroundItemDefinition.Pack(OutboundRemoveGroundItem(message))

	case protocol.OutboundSetInterface:
		return OutboundSetInterfaceDefinition.Pack(OutboundSetInterface(message))

	case protocol.OutboundScriptEvent:
		return OutboundScriptEventDefinition.Pack(OutboundScriptEvent(message))

	case protocol.OutboundUpdateInventoryItem:
		return OutboundUpdateInventoryItemDefinition.Pack(OutboundUpdateInventoryItem(message))

	case protocol.PlayerUpdate:
		return PlayerUpdateDefinition.Pack(PlayerUpdate(message))

	case protocol.OutboundRegionUpdate:
		return OutboundRegionUpdateDefinition.Pack(OutboundRegionUpdate(message))

	case protocol.OutboundCreateGroundItem:
		return OutboundCreateGroundItemDefinition.Pack(OutboundCreateGroundItem(message))

	case protocol.OutboundUpdateAllInventoryItems:
		return OutboundUpdateAllInventoryItemsDefinition.Pack(OutboundUpdateAllInventoryItems(message))

	case protocol.OutboundLoginResponse:
		return OutboundLoginResponse(message)

	case protocol.OutboundInitInterface:
		return OutboundInitInterface(message)

	case protocol.OutboundTabInterface:
		return OutboundTabInterface(message)

	case protocol.OutboundSetText:
		fmt.Println("OutboundSetText not implemented")
		return nil

	case protocol.OutboundDnsLookup:
		fmt.Println("OutboundDnsLookup not implemented")
		return nil

	case protocol.OutboundLogout:
		fmt.Println("OutboundLogout not implemented")
		return nil

	case protocol.OutboundResetCamera:
		fmt.Println("OutboundResetCamera not implemented")
		return nil

	case protocol.OutboundCreateGlobalGroundItem:
		fmt.Println("OutboundCreateGlobalGroundItem not implemented")
		return nil

	case protocol.OutboundPlayerInit:
		fmt.Println("OutboundPlayerInit not implemented")
		return nil

	}
	panic(fmt.Sprintf("cannot encode %T", message))
}
