// Code generated by "stringer -type=AuthResponse"; DO NOT EDIT.

package auth

import "strconv"

const (
	_AuthResponse_name_0 = "AuthPendingAuthDelayAuthOkayAuthInvalidCredentialsAuthDisabledAuthDuplicateSessionAuthUpdatesAuthServerFullAuthNoLoginServerAuthTooManyConnectionsAuthBadSessionIdAuthRejectedAuthMembersWorldAuthIncompleteAuthUpdatingAuthUnknownAuthAttemptsExceededAuthMembersArea"
	_AuthResponse_name_1 = "AuthInvalidLoginServerAuthInvalidTransferringAuthEnd"
)

var (
	_AuthResponse_index_0 = [...]uint16{0, 11, 20, 28, 50, 62, 82, 93, 107, 124, 146, 162, 174, 190, 204, 216, 227, 247, 262}
	_AuthResponse_index_1 = [...]uint8{0, 22, 45, 52}
)

func (i AuthResponse) String() string {
	switch {
	case 0 <= i && i <= 17:
		return _AuthResponse_name_0[_AuthResponse_index_0[i]:_AuthResponse_index_0[i+1]]
	case 20 <= i && i <= 22:
		i -= 20
		return _AuthResponse_name_1[_AuthResponse_index_1[i]:_AuthResponse_index_1[i+1]]
	default:
		return "AuthResponse(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
