// Generated by gopygen; DO NOT EDIT
package server

import (
	"fmt"
	"sync"

	"github.com/qur/gopy/lib"
	"gopkg.in/tomb.v2"

	"github.com/tgascoigne/gopygen/gopygen"
)

// Sometimes we might generate code which doesn't use some of the above imports
// Use them here just in case
var _ = fmt.Sprintf("")
var _ = gopygen.Dummy

var ServerDef = py.Class{
	Name:    "Server",
	Flags:   py.TPFLAGS_BASETYPE,
	Pointer: (*Server)(nil),
}

// Registers this type with a python module
func RegisterServer(module *py.Module) error {
	var err error
	var class *py.Type
	if class, err = ServerDef.Create(); err != nil {
		return err
	}

	if err = module.AddObject("Server", class); err != nil {
		return err
	}

	return nil
}

// Alloc allocates an object for use in python land.
// Copies the member fields from this object to the newly allocated object
// Usage: obj := GoObject{X:1, Y: 2}.Alloc()
func NewServer(arg_0 string) (*Server, error) {
	lock := py.NewLock()
	defer lock.Unlock()

	// Allocate
	alloc_, err := ServerDef.Alloc(0)
	if err != nil {
		return nil, err
	}
	alloc := alloc_.(*Server)
	err = alloc.Init(arg_0)
	return alloc, err
}

func (obj *Server) PyInit(_args *py.Tuple, kwds *py.Dict) error {
	lock := py.NewLock()
	defer lock.Unlock()

	var err error
	_ = err
	args := _args.Slice()
	if len(args) != 1 {
		return fmt.Errorf("(Server) PyInit: parameter length mismatch")
	}

	args[0].Incref()
	in_0, err := gopygen.TypeConvIn(args[0], "string")
	if err != nil {
		return err
	}

	err = obj.Init(in_0.(string))

	args[0].Decref()

	return err
}

func (obj *Server) PyGet_m() (py.Object, error) {
	return gopygen.TypeConvOut(obj.m, "sync.Mutex")
}

func (obj *Server) PySet_m(arg py.Object) error {
	arg.Incref()
	val, err := gopygen.TypeConvIn(arg, "sync.Mutex")
	if err != nil {
		return err
	}

	if _, ok := val.(py.Object); ok {
		// If we're not converting it from a python object, we should refcount it properly
		val.(py.Object).Incref()
	}
	arg.Decref()

	var tmp interface{}
	tmp = &obj.m
	obj.m = val.(sync.Mutex)

	if oldObj, ok := tmp.(py.Object); ok {
		// If we're not converting it from a python object, we should refcount it properly
		oldObj.Decref()
	}
	return nil
}

func (obj *Server) PyGet_t() (py.Object, error) {
	return gopygen.TypeConvOut(obj.t, "tomb.Tomb")
}

func (obj *Server) PySet_t(arg py.Object) error {
	arg.Incref()
	val, err := gopygen.TypeConvIn(arg, "tomb.Tomb")
	if err != nil {
		return err
	}

	if _, ok := val.(py.Object); ok {
		// If we're not converting it from a python object, we should refcount it properly
		val.(py.Object).Incref()
	}
	arg.Decref()

	var tmp interface{}
	tmp = &obj.t
	obj.t = val.(tomb.Tomb)

	if oldObj, ok := tmp.(py.Object); ok {
		// If we're not converting it from a python object, we should refcount it properly
		oldObj.Decref()
	}
	return nil
}

func (s *Server) Py_SetService(_args *py.Tuple, kwds *py.Dict) (py.Object, error) {
	lock := py.NewLock()
	defer lock.Unlock()

	var err error
	_ = err
	args := _args.Slice()
	if len(args) != 2 {
		return nil, fmt.Errorf("Py_SetService: parameter length mismatch")
	}
	// Convert parameters

	args[0].Incref()
	in_0, err := gopygen.TypeConvIn(args[0], "int")
	if err != nil {
		return nil, err
	}

	args[1].Incref()
	in_1, err := gopygen.TypeConvIn(args[1], "Service")
	if err != nil {
		return nil, err
	}

	// Make the function call

	s.SetService(in_0.(int), in_1.(Service))

	// Remove local references

	args[0].Decref()

	args[1].Decref()

	py.None.Incref()
	return py.None, nil

}

func (s *Server) Py_Start(_args *py.Tuple, kwds *py.Dict) (py.Object, error) {
	lock := py.NewLock()
	defer lock.Unlock()

	var err error
	_ = err
	args := _args.Slice()
	if len(args) != 0 {
		return nil, fmt.Errorf("Py_Start: parameter length mismatch")
	}
	// Convert parameters

	// Make the function call

	res0 := s.Start()

	// Remove local references

	out_0, err := gopygen.TypeConvOut(res0, "error")
	if err != nil {
		return nil, err
	}

	return out_0, nil

}

func (s *Server) Py_Stop(_args *py.Tuple, kwds *py.Dict) (py.Object, error) {
	lock := py.NewLock()
	defer lock.Unlock()

	var err error
	_ = err
	args := _args.Slice()
	if len(args) != 0 {
		return nil, fmt.Errorf("Py_Stop: parameter length mismatch")
	}
	// Convert parameters

	// Make the function call

	res0 := s.Stop()

	// Remove local references

	out_0, err := gopygen.TypeConvOut(res0, "error")
	if err != nil {
		return nil, err
	}

	return out_0, nil

}
