// Code generated by bbc; DO NOT EDIT.
package game_protocol

import (
	"io"

	"github.com/gemrs/gem/gem/encoding"
)

type OutboundPlayerChatMessage struct {
	Effects       encoding.Uint8
	Colour        encoding.Uint8
	Rights        encoding.Uint8
	Length        encoding.Uint8
	PackedMessage encoding.Bytes
}

func (struc *OutboundPlayerChatMessage) Encode(buf io.Writer, flags interface{}) (err error) {
	err = struc.Effects.Encode(buf, encoding.IntegerFlag(encoding.IntNilFlag))
	if err != nil {
		return err
	}

	err = struc.Colour.Encode(buf, encoding.IntegerFlag(encoding.IntNilFlag))
	if err != nil {
		return err
	}

	err = struc.Rights.Encode(buf, encoding.IntegerFlag(encoding.IntNilFlag))
	if err != nil {
		return err
	}

	err = struc.Length.Encode(buf, encoding.IntegerFlag(encoding.IntNegate))
	if err != nil {
		return err
	}

	err = struc.PackedMessage.Encode(buf, nil)
	if err != nil {
		return err
	}

	return err
}

func (struc *OutboundPlayerChatMessage) Decode(buf io.Reader, flags interface{}) (err error) {
	err = struc.Effects.Decode(buf, encoding.IntegerFlag(encoding.IntNilFlag))
	if err != nil {
		return err
	}

	err = struc.Colour.Decode(buf, encoding.IntegerFlag(encoding.IntNilFlag))
	if err != nil {
		return err
	}

	err = struc.Rights.Decode(buf, encoding.IntegerFlag(encoding.IntNilFlag))
	if err != nil {
		return err
	}

	err = struc.Length.Decode(buf, encoding.IntegerFlag(encoding.IntNegate))
	if err != nil {
		return err
	}

	err = struc.PackedMessage.Decode(buf, nil)
	if err != nil {
		return err
	}

	return err
}

type OutboundSkill anonymous_outbound_packets_bb_4

var OutboundSkillDefinition = encoding.PacketHeader{
	Type:   (*OutboundSkill)(nil),
	Number: 134,
	Size:   encoding.SzFixed,
}

func (frm *OutboundSkill) Encode(buf io.Writer, flags interface{}) (err error) {
	struc := (*anonymous_outbound_packets_bb_4)(frm)
	hdr := encoding.PacketHeader{
		Number: OutboundSkillDefinition.Number,
		Size:   OutboundSkillDefinition.Size,
		Object: struc,
	}
	return hdr.Encode(buf, flags)
}

func (frm *OutboundSkill) Decode(buf io.Reader, flags interface{}) (err error) {
	struc := (*anonymous_outbound_packets_bb_4)(frm)
	hdr := encoding.PacketHeader{
		Number: OutboundSkillDefinition.Number,
		Size:   OutboundSkillDefinition.Size,
		Object: struc,
	}
	return hdr.Decode(buf, flags)
}

type OutboundUpdateInventoryItem anonymous_outbound_packets_bb_8

var OutboundUpdateInventoryItemDefinition = encoding.PacketHeader{
	Type:   (*OutboundUpdateInventoryItem)(nil),
	Number: 34,
	Size:   encoding.SzVar16,
}

func (frm *OutboundUpdateInventoryItem) Encode(buf io.Writer, flags interface{}) (err error) {
	struc := (*anonymous_outbound_packets_bb_8)(frm)
	hdr := encoding.PacketHeader{
		Number: OutboundUpdateInventoryItemDefinition.Number,
		Size:   OutboundUpdateInventoryItemDefinition.Size,
		Object: struc,
	}
	return hdr.Encode(buf, flags)
}

func (frm *OutboundUpdateInventoryItem) Decode(buf io.Reader, flags interface{}) (err error) {
	struc := (*anonymous_outbound_packets_bb_8)(frm)
	hdr := encoding.PacketHeader{
		Number: OutboundUpdateInventoryItemDefinition.Number,
		Size:   OutboundUpdateInventoryItemDefinition.Size,
		Object: struc,
	}
	return hdr.Decode(buf, flags)
}

type anonymous_outbound_packets_bb_8 struct {
	InventoryID encoding.Uint16
	Slot        encoding.Uint8
	ItemID      encoding.Uint16
	Count       encoding.Uint8
}

func (struc *anonymous_outbound_packets_bb_8) Encode(buf io.Writer, flags interface{}) (err error) {
	err = struc.InventoryID.Encode(buf, encoding.IntegerFlag(encoding.IntNilFlag))
	if err != nil {
		return err
	}

	err = struc.Slot.Encode(buf, encoding.IntegerFlag(encoding.IntNilFlag))
	if err != nil {
		return err
	}

	err = struc.ItemID.Encode(buf, encoding.IntegerFlag(encoding.IntNilFlag))
	if err != nil {
		return err
	}

	err = struc.Count.Encode(buf, encoding.IntegerFlag(encoding.IntNilFlag))
	if err != nil {
		return err
	}

	return err
}

func (struc *anonymous_outbound_packets_bb_8) Decode(buf io.Reader, flags interface{}) (err error) {
	err = struc.InventoryID.Decode(buf, encoding.IntegerFlag(encoding.IntNilFlag))
	if err != nil {
		return err
	}

	err = struc.Slot.Decode(buf, encoding.IntegerFlag(encoding.IntNilFlag))
	if err != nil {
		return err
	}

	err = struc.ItemID.Decode(buf, encoding.IntegerFlag(encoding.IntNilFlag))
	if err != nil {
		return err
	}

	err = struc.Count.Decode(buf, encoding.IntegerFlag(encoding.IntNilFlag))
	if err != nil {
		return err
	}

	return err
}

type anonymous_outbound_packets_bb_1 struct {
	Message encoding.JString
}

func (struc *anonymous_outbound_packets_bb_1) Encode(buf io.Writer, flags interface{}) (err error) {
	err = struc.Message.Encode(buf, 0)
	if err != nil {
		return err
	}

	return err
}

func (struc *anonymous_outbound_packets_bb_1) Decode(buf io.Reader, flags interface{}) (err error) {
	err = struc.Message.Decode(buf, 0)
	if err != nil {
		return err
	}

	return err
}

type anonymous_outbound_packets_bb_3 struct {
	InterfaceID encoding.Uint16
	Tab         encoding.Uint8
}

func (struc *anonymous_outbound_packets_bb_3) Encode(buf io.Writer, flags interface{}) (err error) {
	err = struc.InterfaceID.Encode(buf, encoding.IntegerFlag(encoding.IntNilFlag))
	if err != nil {
		return err
	}

	err = struc.Tab.Encode(buf, encoding.IntegerFlag(encoding.IntOffset128))
	if err != nil {
		return err
	}

	return err
}

func (struc *anonymous_outbound_packets_bb_3) Decode(buf io.Reader, flags interface{}) (err error) {
	err = struc.InterfaceID.Decode(buf, encoding.IntegerFlag(encoding.IntNilFlag))
	if err != nil {
		return err
	}

	err = struc.Tab.Decode(buf, encoding.IntegerFlag(encoding.IntOffset128))
	if err != nil {
		return err
	}

	return err
}

type anonymous_outbound_packets_bb_4 struct {
	Skill      encoding.Uint8
	Experience encoding.Uint32
	Level      encoding.Uint8
}

func (struc *anonymous_outbound_packets_bb_4) Encode(buf io.Writer, flags interface{}) (err error) {
	err = struc.Skill.Encode(buf, encoding.IntegerFlag(encoding.IntNilFlag))
	if err != nil {
		return err
	}

	err = struc.Experience.Encode(buf, encoding.IntegerFlag(encoding.IntPDPEndian))
	if err != nil {
		return err
	}

	err = struc.Level.Encode(buf, encoding.IntegerFlag(encoding.IntNilFlag))
	if err != nil {
		return err
	}

	return err
}

func (struc *anonymous_outbound_packets_bb_4) Decode(buf io.Reader, flags interface{}) (err error) {
	err = struc.Skill.Decode(buf, encoding.IntegerFlag(encoding.IntNilFlag))
	if err != nil {
		return err
	}

	err = struc.Experience.Decode(buf, encoding.IntegerFlag(encoding.IntPDPEndian))
	if err != nil {
		return err
	}

	err = struc.Level.Decode(buf, encoding.IntegerFlag(encoding.IntNilFlag))
	if err != nil {
		return err
	}

	return err
}

type OutboundLogout anonymous_outbound_packets_bb_5

var OutboundLogoutDefinition = encoding.PacketHeader{
	Type:   (*OutboundLogout)(nil),
	Number: 109,
	Size:   encoding.SzFixed,
}

func (frm *OutboundLogout) Encode(buf io.Writer, flags interface{}) (err error) {
	struc := (*anonymous_outbound_packets_bb_5)(frm)
	hdr := encoding.PacketHeader{
		Number: OutboundLogoutDefinition.Number,
		Size:   OutboundLogoutDefinition.Size,
		Object: struc,
	}
	return hdr.Encode(buf, flags)
}

func (frm *OutboundLogout) Decode(buf io.Reader, flags interface{}) (err error) {
	struc := (*anonymous_outbound_packets_bb_5)(frm)
	hdr := encoding.PacketHeader{
		Number: OutboundLogoutDefinition.Number,
		Size:   OutboundLogoutDefinition.Size,
		Object: struc,
	}
	return hdr.Decode(buf, flags)
}

type anonymous_outbound_packets_bb_6 struct {
	Text encoding.JString
	Id   encoding.Uint16
}

func (struc *anonymous_outbound_packets_bb_6) Encode(buf io.Writer, flags interface{}) (err error) {
	err = struc.Text.Encode(buf, 0)
	if err != nil {
		return err
	}

	err = struc.Id.Encode(buf, encoding.IntegerFlag(encoding.IntLittleEndian|encoding.IntInverse128))
	if err != nil {
		return err
	}

	return err
}

func (struc *anonymous_outbound_packets_bb_6) Decode(buf io.Reader, flags interface{}) (err error) {
	err = struc.Text.Decode(buf, 0)
	if err != nil {
		return err
	}

	err = struc.Id.Decode(buf, encoding.IntegerFlag(encoding.IntLittleEndian|encoding.IntInverse128))
	if err != nil {
		return err
	}

	return err
}

type OutboundSetText anonymous_outbound_packets_bb_6

var OutboundSetTextDefinition = encoding.PacketHeader{
	Type:   (*OutboundSetText)(nil),
	Number: 126,
	Size:   encoding.SzVar16,
}

func (frm *OutboundSetText) Encode(buf io.Writer, flags interface{}) (err error) {
	struc := (*anonymous_outbound_packets_bb_6)(frm)
	hdr := encoding.PacketHeader{
		Number: OutboundSetTextDefinition.Number,
		Size:   OutboundSetTextDefinition.Size,
		Object: struc,
	}
	return hdr.Encode(buf, flags)
}

func (frm *OutboundSetText) Decode(buf io.Reader, flags interface{}) (err error) {
	struc := (*anonymous_outbound_packets_bb_6)(frm)
	hdr := encoding.PacketHeader{
		Number: OutboundSetTextDefinition.Number,
		Size:   OutboundSetTextDefinition.Size,
		Object: struc,
	}
	return hdr.Decode(buf, flags)
}

type OutboundPlayerInit anonymous_outbound_packets_bb_7

var OutboundPlayerInitDefinition = encoding.PacketHeader{
	Type:   (*OutboundPlayerInit)(nil),
	Number: 249,
	Size:   encoding.SzFixed,
}

func (frm *OutboundPlayerInit) Encode(buf io.Writer, flags interface{}) (err error) {
	struc := (*anonymous_outbound_packets_bb_7)(frm)
	hdr := encoding.PacketHeader{
		Number: OutboundPlayerInitDefinition.Number,
		Size:   OutboundPlayerInitDefinition.Size,
		Object: struc,
	}
	return hdr.Encode(buf, flags)
}

func (frm *OutboundPlayerInit) Decode(buf io.Reader, flags interface{}) (err error) {
	struc := (*anonymous_outbound_packets_bb_7)(frm)
	hdr := encoding.PacketHeader{
		Number: OutboundPlayerInitDefinition.Number,
		Size:   OutboundPlayerInitDefinition.Size,
		Object: struc,
	}
	return hdr.Decode(buf, flags)
}

type anonymous_outbound_packets_bb_0 struct {
	SectorX encoding.Uint16
	SectorY encoding.Uint16
}

func (struc *anonymous_outbound_packets_bb_0) Encode(buf io.Writer, flags interface{}) (err error) {
	err = struc.SectorX.Encode(buf, encoding.IntegerFlag(encoding.IntOffset128))
	if err != nil {
		return err
	}

	err = struc.SectorY.Encode(buf, encoding.IntegerFlag(encoding.IntNilFlag))
	if err != nil {
		return err
	}

	return err
}

func (struc *anonymous_outbound_packets_bb_0) Decode(buf io.Reader, flags interface{}) (err error) {
	err = struc.SectorX.Decode(buf, encoding.IntegerFlag(encoding.IntOffset128))
	if err != nil {
		return err
	}

	err = struc.SectorY.Decode(buf, encoding.IntegerFlag(encoding.IntNilFlag))
	if err != nil {
		return err
	}

	return err
}

type anonymous_outbound_packets_bb_5 struct {
}

func (struc *anonymous_outbound_packets_bb_5) Encode(buf io.Writer, flags interface{}) (err error) {

	return err
}

func (struc *anonymous_outbound_packets_bb_5) Decode(buf io.Reader, flags interface{}) (err error) {

	return err
}

type OutboundRegionUpdate anonymous_outbound_packets_bb_0

var OutboundRegionUpdateDefinition = encoding.PacketHeader{
	Type:   (*OutboundRegionUpdate)(nil),
	Number: 73,
	Size:   encoding.SzFixed,
}

func (frm *OutboundRegionUpdate) Encode(buf io.Writer, flags interface{}) (err error) {
	struc := (*anonymous_outbound_packets_bb_0)(frm)
	hdr := encoding.PacketHeader{
		Number: OutboundRegionUpdateDefinition.Number,
		Size:   OutboundRegionUpdateDefinition.Size,
		Object: struc,
	}
	return hdr.Encode(buf, flags)
}

func (frm *OutboundRegionUpdate) Decode(buf io.Reader, flags interface{}) (err error) {
	struc := (*anonymous_outbound_packets_bb_0)(frm)
	hdr := encoding.PacketHeader{
		Number: OutboundRegionUpdateDefinition.Number,
		Size:   OutboundRegionUpdateDefinition.Size,
		Object: struc,
	}
	return hdr.Decode(buf, flags)
}

type OutboundChatMessage anonymous_outbound_packets_bb_1

var OutboundChatMessageDefinition = encoding.PacketHeader{
	Type:   (*OutboundChatMessage)(nil),
	Number: 253,
	Size:   encoding.SzVar8,
}

func (frm *OutboundChatMessage) Encode(buf io.Writer, flags interface{}) (err error) {
	struc := (*anonymous_outbound_packets_bb_1)(frm)
	hdr := encoding.PacketHeader{
		Number: OutboundChatMessageDefinition.Number,
		Size:   OutboundChatMessageDefinition.Size,
		Object: struc,
	}
	return hdr.Encode(buf, flags)
}

func (frm *OutboundChatMessage) Decode(buf io.Reader, flags interface{}) (err error) {
	struc := (*anonymous_outbound_packets_bb_1)(frm)
	hdr := encoding.PacketHeader{
		Number: OutboundChatMessageDefinition.Number,
		Size:   OutboundChatMessageDefinition.Size,
		Object: struc,
	}
	return hdr.Decode(buf, flags)
}

type OutboundTabInterface anonymous_outbound_packets_bb_3

var OutboundTabInterfaceDefinition = encoding.PacketHeader{
	Type:   (*OutboundTabInterface)(nil),
	Number: 71,
	Size:   encoding.SzFixed,
}

func (frm *OutboundTabInterface) Encode(buf io.Writer, flags interface{}) (err error) {
	struc := (*anonymous_outbound_packets_bb_3)(frm)
	hdr := encoding.PacketHeader{
		Number: OutboundTabInterfaceDefinition.Number,
		Size:   OutboundTabInterfaceDefinition.Size,
		Object: struc,
	}
	return hdr.Encode(buf, flags)
}

func (frm *OutboundTabInterface) Decode(buf io.Reader, flags interface{}) (err error) {
	struc := (*anonymous_outbound_packets_bb_3)(frm)
	hdr := encoding.PacketHeader{
		Number: OutboundTabInterfaceDefinition.Number,
		Size:   OutboundTabInterfaceDefinition.Size,
		Object: struc,
	}
	return hdr.Decode(buf, flags)
}

type anonymous_outbound_packets_bb_7 struct {
	Membership encoding.Uint8
	Index      encoding.Uint16
}

func (struc *anonymous_outbound_packets_bb_7) Encode(buf io.Writer, flags interface{}) (err error) {
	err = struc.Membership.Encode(buf, encoding.IntegerFlag(encoding.IntOffset128))
	if err != nil {
		return err
	}

	err = struc.Index.Encode(buf, encoding.IntegerFlag(encoding.IntOffset128))
	if err != nil {
		return err
	}

	return err
}

func (struc *anonymous_outbound_packets_bb_7) Decode(buf io.Reader, flags interface{}) (err error) {
	err = struc.Membership.Decode(buf, encoding.IntegerFlag(encoding.IntOffset128))
	if err != nil {
		return err
	}

	err = struc.Index.Decode(buf, encoding.IntegerFlag(encoding.IntOffset128))
	if err != nil {
		return err
	}

	return err
}
