// Code generated by gem_gen; DO NOT EDIT.
package protocol_os_161

import (
	"fmt"

	"github.com/gemrs/gem/gem/core/encoding"
	"github.com/gemrs/gem/gem/game/server"
	"github.com/gemrs/gem/gem/protocol"
)

var InboundCommandDefinition = InboundPacketDefinition{
	Number: 93,
	Size:   SzVar8,
}

var OutboundUpdateInventoryItemDefinition = OutboundPacketDefinition{
	Number: 24,
	Size:   SzVar16,
}

var OutboundSetRootInterfaceDefinition = OutboundPacketDefinition{
	Number: 2,
	Size:   SzFixed,
}

var InboundKeyPressDefinition = InboundPacketDefinition{
	Number: 71,
	Size:   SzVar16,
}

var OutboundRegionUpdateDefinition = OutboundPacketDefinition{
	Number: 78,
	Size:   SzVar16,
}

var OutboundChatMessageDefinition = OutboundPacketDefinition{
	Number: 44,
	Size:   SzVar8,
}

var OutboundUpdateAllInventoryItemsDefinition = OutboundPacketDefinition{
	Number: 52,
	Size:   SzVar16,
}

var InboundCameraMovementDefinition = InboundPacketDefinition{
	Number: 84,
	Size:   SzFixed,
}

var InboundWindowFocusDefinition = InboundPacketDefinition{
	Number: 41,
	Size:   SzFixed,
}

var OutboundScriptEventDefinition = OutboundPacketDefinition{
	Number: 76,
	Size:   SzVar16,
}

var InboundPingDefinition = InboundPacketDefinition{
	Number: 63,
	Size:   SzFixed,
}

var PlayerUpdateDefinition = OutboundPacketDefinition{
	Number: 48,
	Size:   SzVar16,
}

var InboundMouseMovementDefinition = InboundPacketDefinition{
	Number: 88,
	Size:   SzVar8,
}

var OutboundSetInterfaceDefinition = OutboundPacketDefinition{
	Number: 34,
	Size:   SzFixed,
}

var InboundPlayerWalkDefinition = InboundPacketDefinition{
	Number: 65,
	Size:   SzVar8,
}

var InboundMouseClickDefinition = InboundPacketDefinition{
	Number: 3,
	Size:   SzFixed,
}

var InboundPlayerWalkMapDefinition = InboundPacketDefinition{
	Number: 6,
	Size:   SzVar8,
}

var OutboundSkillDefinition = OutboundPacketDefinition{
	Number: 0,
	Size:   SzFixed,
}

var OutboundResetCameraDefinition = OutboundPacketDefinition{
	Number: 49,
	Size:   SzFixed,
}

var inboundPacketBuilders = map[int]func() encoding.Decodable{

	93: func() encoding.Decodable {
		return &PacketHeader{
			Number: InboundCommandDefinition.Number,
			Size:   InboundCommandDefinition.Size,
			Object: new(InboundCommand),
		}
	},

	71: func() encoding.Decodable {
		return &PacketHeader{
			Number: InboundKeyPressDefinition.Number,
			Size:   InboundKeyPressDefinition.Size,
			Object: new(InboundKeyPress),
		}
	},

	84: func() encoding.Decodable {
		return &PacketHeader{
			Number: InboundCameraMovementDefinition.Number,
			Size:   InboundCameraMovementDefinition.Size,
			Object: new(InboundCameraMovement),
		}
	},

	41: func() encoding.Decodable {
		return &PacketHeader{
			Number: InboundWindowFocusDefinition.Number,
			Size:   InboundWindowFocusDefinition.Size,
			Object: new(InboundWindowFocus),
		}
	},

	63: func() encoding.Decodable {
		return &PacketHeader{
			Number: InboundPingDefinition.Number,
			Size:   InboundPingDefinition.Size,
			Object: new(InboundPing),
		}
	},

	88: func() encoding.Decodable {
		return &PacketHeader{
			Number: InboundMouseMovementDefinition.Number,
			Size:   InboundMouseMovementDefinition.Size,
			Object: new(InboundMouseMovement),
		}
	},

	65: func() encoding.Decodable {
		return &PacketHeader{
			Number: InboundPlayerWalkDefinition.Number,
			Size:   InboundPlayerWalkDefinition.Size,
			Object: new(InboundPlayerWalk),
		}
	},

	3: func() encoding.Decodable {
		return &PacketHeader{
			Number: InboundMouseClickDefinition.Number,
			Size:   InboundMouseClickDefinition.Size,
			Object: new(InboundMouseClick),
		}
	},

	6: func() encoding.Decodable {
		return &PacketHeader{
			Number: InboundPlayerWalkMapDefinition.Number,
			Size:   InboundPlayerWalkMapDefinition.Size,
			Object: new(InboundPlayerWalkMap),
		}
	},
}

func (p protocolImpl) Decode(message encoding.Decodable) server.Message {
	switch message := message.(type) {

	case *InboundCommand:
		return (*protocol.InboundCommand)(message)

	case *InboundKeyPress:
		return (*protocol.InboundKeyPress)(message)

	case *InboundCameraMovement:
		return (*protocol.InboundCameraMovement)(message)

	case *InboundWindowFocus:
		return (*protocol.InboundWindowFocus)(message)

	case *InboundPing:
		return (*protocol.InboundPing)(message)

	case *InboundMouseMovement:
		return (*protocol.InboundMouseMovement)(message)

	case *InboundPlayerWalk:
		return (*protocol.InboundPlayerWalk)(message)

	case *InboundMouseClick:
		return (*protocol.InboundMouseClick)(message)

	case *InboundPlayerWalkMap:
		return (*protocol.InboundPlayerWalk)(message)

	case *UnknownPacket:
		return (*protocol.UnknownPacket)(message)

	case *PacketHeader:
		return p.Decode(message.Object.(encoding.Decodable))
	}
	panic(fmt.Sprintf("cannot decode %T", message))
}

func (protocolImpl) Encode(message server.Message) encoding.Encodable {
	switch message := message.(type) {

	case protocol.OutboundUpdateInventoryItem:
		return OutboundUpdateInventoryItemDefinition.Pack(OutboundUpdateInventoryItem(message))

	case protocol.OutboundSetRootInterface:
		return OutboundSetRootInterfaceDefinition.Pack(OutboundSetRootInterface(message))

	case protocol.OutboundRegionUpdate:
		return OutboundRegionUpdateDefinition.Pack(OutboundRegionUpdate(message))

	case protocol.OutboundChatMessage:
		return OutboundChatMessageDefinition.Pack(OutboundChatMessage(message))

	case protocol.OutboundUpdateAllInventoryItems:
		return OutboundUpdateAllInventoryItemsDefinition.Pack(OutboundUpdateAllInventoryItems(message))

	case protocol.OutboundScriptEvent:
		return OutboundScriptEventDefinition.Pack(OutboundScriptEvent(message))

	case protocol.PlayerUpdate:
		return PlayerUpdateDefinition.Pack(PlayerUpdate(message))

	case protocol.OutboundSetInterface:
		return OutboundSetInterfaceDefinition.Pack(OutboundSetInterface(message))

	case protocol.OutboundSkill:
		return OutboundSkillDefinition.Pack(OutboundSkill(message))

	case protocol.OutboundResetCamera:
		return OutboundResetCameraDefinition.Pack(OutboundResetCamera(message))

	case protocol.OutboundInitInterface:
		return OutboundInitInterface(message)

	case protocol.OutboundLoginResponse:
		return OutboundLoginResponse(message)

	case protocol.OutboundTabInterface:
		return OutboundTabInterface(message)

	case protocol.OutboundCreateGlobalGroundItem:
		fmt.Println("OutboundCreateGlobalGroundItem not implemented")
		return nil

	case protocol.OutboundRemoveGroundItem:
		fmt.Println("OutboundRemoveGroundItem not implemented")
		return nil

	case protocol.OutboundCreateGroundItem:
		fmt.Println("OutboundCreateGroundItem not implemented")
		return nil

	case protocol.OutboundSetText:
		fmt.Println("OutboundSetText not implemented")
		return nil

	case protocol.OutboundLogout:
		fmt.Println("OutboundLogout not implemented")
		return nil

	case protocol.OutboundDnsLookup:
		fmt.Println("OutboundDnsLookup not implemented")
		return nil

	case protocol.OutboundSectorUpdate:
		fmt.Println("OutboundSectorUpdate not implemented")
		return nil

	case protocol.OutboundPlayerInit:
		fmt.Println("OutboundPlayerInit not implemented")
		return nil

	}
	panic(fmt.Sprintf("cannot encode %T", message))
}
