// Code generated by gem_gen; DO NOT EDIT.
package protocol_os_161

import (
	"fmt"

	"github.com/gemrs/gem/gem/core/encoding"
	"github.com/gemrs/gem/gem/game/server"
	"github.com/gemrs/gem/gem/protocol"
)

var OutboundSetInterfaceDefinition = OutboundPacketDefinition{
	Number: 34,
	Size:   SzFixed,
}

var OutboundResetCameraDefinition = OutboundPacketDefinition{
	Number: 49,
	Size:   SzFixed,
}

var OutboundSkillDefinition = OutboundPacketDefinition{
	Number: 0,
	Size:   SzFixed,
}

var OutboundSetRootInterfaceDefinition = OutboundPacketDefinition{
	Number: 2,
	Size:   SzFixed,
}

var OutboundRegionUpdateDefinition = OutboundPacketDefinition{
	Number: 78,
	Size:   SzVar16,
}

var InboundPlayerWalkMapDefinition = InboundPacketDefinition{
	Number: 6,
	Size:   SzVar8,
}

var PlayerUpdateDefinition = OutboundPacketDefinition{
	Number: 48,
	Size:   SzVar16,
}

var OutboundScriptEventDefinition = OutboundPacketDefinition{
	Number: 76,
	Size:   SzVar16,
}

var InboundPlayerWalkDefinition = InboundPacketDefinition{
	Number: 65,
	Size:   SzVar8,
}

var inboundPacketBuilders = map[int]func() encoding.Decodable{

	6: func() encoding.Decodable {
		return &PacketHeader{
			Number: InboundPlayerWalkMapDefinition.Number,
			Size:   InboundPlayerWalkMapDefinition.Size,
			Object: new(InboundPlayerWalkMap),
		}
	},

	65: func() encoding.Decodable {
		return &PacketHeader{
			Number: InboundPlayerWalkDefinition.Number,
			Size:   InboundPlayerWalkDefinition.Size,
			Object: new(InboundPlayerWalk),
		}
	},
}

func (p protocolImpl) Decode(message encoding.Decodable) server.Message {
	switch message := message.(type) {

	case *InboundPlayerWalkMap:
		return (*protocol.InboundPlayerWalk)(message)

	case *InboundPlayerWalk:
		return (*protocol.InboundPlayerWalk)(message)

	case *UnknownPacket:
		return (*protocol.UnknownPacket)(message)

	case *PacketHeader:
		return p.Decode(message.Object.(encoding.Decodable))
	}
	panic(fmt.Sprintf("cannot decode %T", message))
}

func (protocolImpl) Encode(message server.Message) encoding.Encodable {
	switch message := message.(type) {

	case protocol.OutboundSetInterface:
		return OutboundSetInterfaceDefinition.Pack(OutboundSetInterface(message))

	case protocol.OutboundResetCamera:
		return OutboundResetCameraDefinition.Pack(OutboundResetCamera(message))

	case protocol.OutboundSkill:
		return OutboundSkillDefinition.Pack(OutboundSkill(message))

	case protocol.OutboundSetRootInterface:
		return OutboundSetRootInterfaceDefinition.Pack(OutboundSetRootInterface(message))

	case protocol.OutboundRegionUpdate:
		return OutboundRegionUpdateDefinition.Pack(OutboundRegionUpdate(message))

	case protocol.PlayerUpdate:
		return PlayerUpdateDefinition.Pack(PlayerUpdate(message))

	case protocol.OutboundScriptEvent:
		return OutboundScriptEventDefinition.Pack(OutboundScriptEvent(message))

	case protocol.OutboundInitInterface:
		return OutboundInitInterface(message)

	case protocol.OutboundTabInterface:
		return OutboundTabInterface(message)

	case protocol.OutboundLoginResponse:
		return OutboundLoginResponse(message)

	case protocol.OutboundUpdateInventoryItem:
		fmt.Println("OutboundUpdateInventoryItem not implemented")
		return nil

	case protocol.OutboundSectorUpdate:
		fmt.Println("OutboundSectorUpdate not implemented")
		return nil

	case protocol.OutboundCreateGroundItem:
		fmt.Println("OutboundCreateGroundItem not implemented")
		return nil

	case protocol.OutboundRemoveGroundItem:
		fmt.Println("OutboundRemoveGroundItem not implemented")
		return nil

	case protocol.OutboundCreateGlobalGroundItem:
		fmt.Println("OutboundCreateGlobalGroundItem not implemented")
		return nil

	case protocol.OutboundLogout:
		fmt.Println("OutboundLogout not implemented")
		return nil

	case protocol.OutboundPlayerInit:
		fmt.Println("OutboundPlayerInit not implemented")
		return nil

	case protocol.OutboundSetText:
		fmt.Println("OutboundSetText not implemented")
		return nil

	case protocol.OutboundDnsLookup:
		fmt.Println("OutboundDnsLookup not implemented")
		return nil

	case protocol.OutboundChatMessage:
		fmt.Println("OutboundChatMessage not implemented")
		return nil

	}
	panic(fmt.Sprintf("cannot encode %T", message))
}
