package entity

import (
	"github.com/sinusoids/gem/gem/game/position"
)

// A SimpleWaypointQueue trusts the points generated by the client and does
// simple interpolation to determine the next position.
// In future, we might want to create another implementation which performs
// server-side path finding
type SimpleWaypointQueue struct {
	points []*position.Absolute
}

// Empty determines if there are any points queued
func (q SimpleWaypointQueue) Empty() bool {
	return len(q.points) == 0
}

// Clear clears the waypoint queue
func (q SimpleWaypointQueue) Clear() {
	q.points = []*position.Absolute{}
}

// Push appends a point to the waypoint queue
func (q SimpleWaypointQueue) Push(point *position.Absolute) {
	q.points = append(q.points, point)
}

// Tick advances the waypoint queue, and returns the next position of the mob
func (q SimpleWaypointQueue) Tick(entity position.Positionable) *position.Absolute {
	return nil
}
