// generated by stringer -type=itemType; DO NOT EDIT

package parse

import "fmt"

const _itemType_name = "itemErroritemEOFitemEOLitemWhiteSpaceitemLeftBrackitemRightBrackitemLeftSquareBrackitemRightSquareBrackitemLeftAngleBrackitemRightAngleBrackitemCommaitemIdentifieritemNumberitemCommentitemKeyworditemFrameitemStructitemStringTypeitemIntTypeitemLenSpecitemFlag"

var _itemType_index = [...]uint16{0, 9, 16, 23, 37, 50, 64, 83, 103, 121, 140, 149, 163, 173, 184, 195, 204, 214, 228, 239, 250, 258}

func (i itemType) String() string {
	if i < 0 || i >= itemType(len(_itemType_index)-1) {
		return fmt.Sprintf("itemType(%d)", i)
	}
	return _itemType_name[_itemType_index[i]:_itemType_index[i+1]]
}
