// Generated by gopygen; DO NOT EDIT
package game

import (
	"fmt"
	"gem/encoding"
	"gem/log"
	"gem/service/game/player"

	"github.com/qur/gopy/lib"
	"github.com/tgascoigne/gopygen/gopygen"
)

// Sometimes we might generate code which doesn't use some of the above imports
// Use them here just in case
var _ = fmt.Sprintf("")
var _ = gopygen.Dummy

var GameConnectionDef = py.Class{
	Name:    "GameConnection",
	Pointer: (*GameConnection)(nil),
}

// Registers this type with a python module
func RegisterGameConnection(module *py.Module) error {
	var err error
	var class *py.Type
	if class, err = GameConnectionDef.Create(); err != nil {
		return err
	}

	if err = module.AddObject("GameConnection", class); err != nil {
		return err
	}

	return nil
}

// Alloc allocates an object for use in python land.
// Copies the member fields from this object to the newly allocated object
// Usage: obj := GoObject{X:1, Y: 2}.Alloc()
func (obj GameConnection) Alloc() (*GameConnection, error) {
	lock := py.NewLock()
	defer lock.Unlock()

	// Allocate
	alloc_, err := GameConnectionDef.Alloc(0)
	if err != nil {
		return nil, err
	}
	alloc := alloc_.(*GameConnection)
	// Copy fields

	alloc.Index = obj.Index

	alloc.Log = obj.Log

	alloc.Session = obj.Session

	alloc.Profile = obj.Profile

	alloc.conn = obj.conn

	alloc.read = obj.read

	alloc.write = obj.write

	alloc.readBuffer = obj.readBuffer

	alloc.writeBuffer = obj.writeBuffer

	alloc.decode = obj.decode

	alloc.disconnect = obj.disconnect

	alloc.canDecode = obj.canDecode

	alloc.active = obj.active

	return alloc, nil
}

func (obj *GameConnection) PyGet_Index() (py.Object, error) {
	return gopygen.TypeConvOut(obj.Index, "Index")
}

func (obj *GameConnection) PySet_Index(arg py.Object) error {
	val, err := gopygen.TypeConvIn(arg, "Index")
	if err != nil {
		return err
	}
	obj.Index = val.(Index)
	return nil
}

func (obj *GameConnection) PyGet_Log() (py.Object, error) {
	return gopygen.TypeConvOut(obj.Log, "*log.Module")
}

func (obj *GameConnection) PySet_Log(arg py.Object) error {
	val, err := gopygen.TypeConvIn(arg, "*log.Module")
	if err != nil {
		return err
	}
	obj.Log = val.(*log.Module)
	return nil
}

func (obj *GameConnection) PyGet_Session() (py.Object, error) {
	return gopygen.TypeConvOut(obj.Session, "*player.Session")
}

func (obj *GameConnection) PySet_Session(arg py.Object) error {
	val, err := gopygen.TypeConvIn(arg, "*player.Session")
	if err != nil {
		return err
	}
	obj.Session = val.(*player.Session)
	return nil
}

func (obj *GameConnection) PyGet_Profile() (py.Object, error) {
	return gopygen.TypeConvOut(obj.Profile, "*player.Profile")
}

func (obj *GameConnection) PySet_Profile(arg py.Object) error {
	val, err := gopygen.TypeConvIn(arg, "*player.Profile")
	if err != nil {
		return err
	}
	obj.Profile = val.(*player.Profile)
	return nil
}

func (conn *GameConnection) Py_Disconnect(_args *py.Tuple, kwds *py.Dict) (py.Object, error) {
	lock := py.NewLock()
	defer lock.Unlock()

	var err error
	_ = err
	args := _args.Slice()
	if len(args) != 0 {
		return nil, fmt.Errorf("Py_Disconnect: parameter length mismatch")
	}

	conn.Disconnect()

	py.None.Incref()
	return py.None, nil

}

func (conn *GameConnection) Py_handshake(_args *py.Tuple, kwds *py.Dict) (py.Object, error) {
	lock := py.NewLock()
	defer lock.Unlock()

	var err error
	_ = err
	args := _args.Slice()
	if len(args) != 2 {
		return nil, fmt.Errorf("Py_handshake: parameter length mismatch")
	}

	in_0, err := gopygen.TypeConvIn(args[0], "*context")
	if err != nil {
		return nil, err
	}

	in_1, err := gopygen.TypeConvIn(args[1], "*encoding.Buffer")
	if err != nil {
		return nil, err
	}

	res0 := conn.handshake(in_0.(*context), in_1.(*encoding.Buffer))

	out_0, err := gopygen.TypeConvOut(res0, "error")
	if err != nil {
		return nil, err
	}

	return out_0, nil

}

func (conn *GameConnection) Py_Write(_args *py.Tuple, kwds *py.Dict) (py.Object, error) {
	lock := py.NewLock()
	defer lock.Unlock()

	var err error
	_ = err
	args := _args.Slice()
	if len(args) != 1 {
		return nil, fmt.Errorf("Py_Write: parameter length mismatch")
	}

	in_0, err := gopygen.TypeConvIn(args[0], "[]byte")
	if err != nil {
		return nil, err
	}

	res0, res1 := conn.Write(in_0.([]byte))

	out_0, err := gopygen.TypeConvOut(res0, "int")
	if err != nil {
		return nil, err
	}

	out_1, err := gopygen.TypeConvOut(res1, "error")
	if err != nil {
		return nil, err
	}

	return py.PackTuple(out_0, out_1)

}

func (conn *GameConnection) Py_flushWriteBuffer(_args *py.Tuple, kwds *py.Dict) (py.Object, error) {
	lock := py.NewLock()
	defer lock.Unlock()

	var err error
	_ = err
	args := _args.Slice()
	if len(args) != 0 {
		return nil, fmt.Errorf("Py_flushWriteBuffer: parameter length mismatch")
	}

	conn.flushWriteBuffer()

	py.None.Incref()
	return py.None, nil

}

func (conn *GameConnection) Py_fillReadBuffer(_args *py.Tuple, kwds *py.Dict) (py.Object, error) {
	lock := py.NewLock()
	defer lock.Unlock()

	var err error
	_ = err
	args := _args.Slice()
	if len(args) != 0 {
		return nil, fmt.Errorf("Py_fillReadBuffer: parameter length mismatch")
	}

	conn.fillReadBuffer()

	py.None.Incref()
	return py.None, nil

}
